# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: current date
        id: date
        run: |
          sudo unlink /etc/localtime
          sudo ln -s /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
          echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
      #- name: Env variables
       # run: |
         # echo "url=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_ENV
        
         # echo "run=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          #echo "ci=$CI" >> $GITHUB_ENV
      - name: variable
        id: env
        run: |
          
          echo "::set-output name=env::$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          echo "::set-output name=num::$GITHUB_RUN_NUMBER"
          echo "::set-output name=ci::$CI"
          
     # - name: print
      #  run: |
       #   ${{ steps.date.outputs.date }}
        #  ${{ steps.env.outputs.env }}
         # ${{ steps.env.outputs.num }}
          #${{ steps.env.outputs.ci }}
      
      - name: set java
        uses: actions/setup-java@v1
        with:
          java-version: 11
        
      - name: Download tomcat
        run: |
            sudo su
            cd /opt/
            wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.63/bin/apache-tomcat-9.0.63.tar.gz
            tar -xvf apache-tomcat-9.0.63.tar.gz
            ls -lrt && pwd
           
            cd /opt/apache-tomcat-9.0.63/webapps && wget -N https://tomcat.apache.org/tomcat-5.5-doc/appdev/sample/sample.war
            /opt/apache-tomcat-9.0.63/bin/startup.sh
            wget -O /dev/null http://localhost:8080/sample 2>&1 | egrep -o "200|failed"  
      - name: call API
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://ip.jsontest.com/'
          method: 'POST'
          contentType: application/json
          data: '{ "property": ["Sites"], "report_type" : ["ALL"] }'                  
                         
      - name: Show Response
        run: echo ${{ steps.myRequest.outputs.response }}
          
